#!/bin/bash

cd /rmf_demos_ws

source /opt/ros/humble/setup.bash
source /rmf_demos_ws/install/setup.bash

# open https://open-rmf.github.io/rmf-panel-js/

ros2 launch rmf_demos_gz_classic office.launch.xml
