#!/bin/bash

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config

docker container prune -f

xhost +local:
rocker --nvidia --x11 \
    --name $CONTAINER_NAME \
    --volume /dev/dri \
    --network host \
    --port 443:443 \
    ${DOCKER_IMAGE_NAME}
