#!/bin/bash

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
source ${PROJECT_ROOT}/config

xhost +local:root 
docker run --privileged --rm -it \
    --name $CONTAINER_NAME \
    -e DISPLAY \
    -e TERM \
    -e QT_X11_NO_MITSHM=1 \
    -e XAUTHORITY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $XAUTHORITY:$XAUTHORITY \
    --net=host \
    --volume="${PROJECT_ROOT}:/rmf_demos_ws/src" \
    -t \
    ${DOCKER_IMAGE_NAME} 
