# FLEET CONFIG =================================================================

rmf_fleet:
  name: "TinyRobot"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22011
    user: "some_user"
    password: "some_password"
  limits:
    linear: [0.5, 0.75]
    angular: [0.6, 2.0]
  profile:
    footprint: 0.3
    vicinity: 0.5
  reversible: True
  battery_system:
    voltage: 12.0
    capacity: 24.0
    charging_current: 5.0
  mechanical_system:
    mass: 2.0
    moment_of_inertia: 10.0
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0
  tool_system:
    power: 0.0
  recharge_threshold: 0.10
  recharge_soc: 1.0 
  publish_fleet_state: 10.0 
  account_for_battery_drain: False
  task_capabilities:
    loop: True
    delivery: True
    clean: False
    finishing_request: "nothing"


robots:
  waver1:
    robot_config:
      max_delay: 15.0
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "charger_3"
        orientation: 0.0
      charger:
        waypoint: "charger_3"

  waver2:
    robot_config:
      max_delay: 15.0
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "charger_2"
        orientation: 0.0
      charger:
        waypoint: "charger_2"
